[package]
description = "OpenEthereum Deep Mind Implementations"
name = "deepmind"
version = "0.0.1"
authors = ["dfuse Developers <developers@dfuse.io>"]

[dependencies]
common-types = { path = "../ethcore/types" }
ethereum-types = "0.9.0"
rustc-hex = "2.1.0"

[features]
default = []
